# Generated by Django 4.0.5 on 2022-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_questions_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('order',), 'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.RemoveField(
            model_name='usersanswers',
            name='answer',
        ),
        migrations.AddField(
            model_name='usersanswers',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
    ]
